services:
  - type: web
    name: intellicompiler-api
    runtime: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && python app.py
    envVars:
      - key: GROQ_API_KEY
        sync: false
    plan: free